### ISSUE TITLE
heroku部署时提示php版本不符合

### ISSUE THREAD

**Issue by Sev73n** [You2php/you2php-heroku#14]
- composer.json/composer.lock requires php 7.1.12 -> no matching package found.
 !     > 
 !     
 !     For reference, the following runtimes are currently available:
 !     
 !     PHP:  7.2.11, 7.2.10, 7.2.9, 7.2.8, 7.2.7, 7.2.6, 7.2.4, 
 !     7.1.23, 7.1.22, 7.1.21, 7.1.20, 7.1.19, 7.1.18, 7.1.16

**Comment by zerohk** [comment]
把composer.json / composer.lock里面PHP版本号改一下就可以了，不知道有没有什么副作用

**Comment by herexf** [comment]
改成7.1.25，两个文件都要改，貌似没问题

**Comment by maossssis** [comment]
实测可行，改为^7.2.0

**Comment by Sev73n** [comment]
改成 7.1.25 成功了
